version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm install -g @angular/cli@^9.1.0
      - run: sudo npm install -g ngh
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Generate Build
        command: ng build --prod --base-href https://petruki.github.io/switcher-management/

      - run:
          command: |
            ngh --token $TOKEN
workflows:
    build-and-test:
      jobs:
        - build-and-test